import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"
      className="container
        mx-auto  w-full flex flex-col h-screen
      "
    >
      <body className="h-full antialiased text-gray-900 bg-gray-100 dark:bg-gray-900 dark:text-gray-100 font-sans" >
        {children}</body >
    </html >
  )
}